/**
 * Control frame's enums list
 */

exports.enums = {
  SYN_STREAM: 1,
  SYN_REPLY: 2,
  RST_STREAM: 3,
  SETTINGS: 4,
  NOOP: 5,
  PING: 6,
  GOAWAY: 7,
  HEADERS: 8,
  WINDOW_UPDATE: 9,
  CONTROL_FLAG_NONE: 0,
  CONTROL_FLAG_FIN: 1,
  CONTROL_FLAG_UNIDIRECTIONAL: 2,
  DATA_FLAG_NONE: 0,
  DATA_FLAG_FIN: 1,
  DATA_FLAG_COMPRESSED: 2,
  PROTOCOL_ERROR: 1,
  INVALID_STREAM: 1,
  REFUSED_STREAM: 2,
  UNSUPPORTED_VERSION: 4,
  CANCEL: 5,
  INTERNAL_ERROR: 6,
  FLOW_CONTROL_ERROR: 7,
  SETTINGS_UPLOAD_BANDWIDTH: 1,
  SETTINGS_DOWNLOAD_BANDWIDTH: 2,
  SETTINGS_ROUND_TRIP_TIME: 3,
  SETTINGS_MAX_CONCURRENT_STREAMS: 4,
  SETTINGS_CURRENT_CWND: 5
};
